/*
 * This file is generated by jOOQ.
*/
package com.leon.taobao.model.taobao.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Message implements Serializable {

    private static final long serialVersionUID = -1735083945;

    private Integer   id;
    private String    content;
    private String    openId;
    private Timestamp createTime;
    private Timestamp updateTime;

    public Message() {}

    public Message(Message value) {
        this.id = value.id;
        this.content = value.content;
        this.openId = value.openId;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public Message(
        Integer   id,
        String    content,
        String    openId,
        Timestamp createTime,
        Timestamp updateTime
    ) {
        this.id = id;
        this.content = content;
        this.openId = openId;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getOpenId() {
        return this.openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Message (");

        sb.append(id);
        sb.append(", ").append(content);
        sb.append(", ").append(openId);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
